name: CD
on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/cd.yml

jobs:
  python-packaging:
    name: 🐍 Packaging
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging.yml@v1.17
    with:
      pure-python: true

  deploy:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: 🚀 Deploy to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mqt.qubomaker
    permissions:
      id-token: write
    needs: [python-packaging]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
